Bug 1754076: make `Request Uplift` interact with Bugzilla
mozilla-conduit/phabricator pull request #16
Opened 2022-02-18 16:33 UTC by cgsheeh

This commit adds interactions with Bugzilla when submitting an
uplift request form on Phabricator. To do this we change the
uplift request comment action from a standard textarea populated
with remarkup for the entire request, into a form with inputs
for each question in the form. We add a custom `form` PHUIXControlType
which takes a spec with a single `questions` field to populate
the values in the form.

We change the type of `DifferentialUpliftRequestCustomField::value`
from a string to a mapping array in all usages, and only convert
the mapping to a string when modifying and accessing from internal
storage. The beta uplift questions array is changed to a mapping of
`questions => defaults` for initial form population. We add a function
`getRemarkup` which converts the field mapping values into a nicely
formatted Remarkup/Markdown string.

Since the above changes allow us to access form fields individually
as typed values, we can now make decisions based on the results of
inputs in the form. We add a code path to interact with Bugzilla
when applying transaction effects (ie saving the new result to
storage). We add a remarkup comment to Bugzilla on the relevant
bug and set the `qe-verify` flag if the user indicated manual QE
testing is required.

2022-02-18 16:37 UTC, cgsheeh commented on moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
> +      }
This is the piece that doesn't work in suite. Before this lands I'll have to clean up some of the stuff in the exception error message, but for now it prints the status code and the object that was sent to Bugzilla.

2022-03-02 17:00 UTC, dklawren requested changes
I am getting the following error when trying to create a new revision for the conduit-suite locally. I am using a sample bug id (2) that I created as well:

FastCGI sent in stderr: "PHP message: [2022-03-02 16:54:06] EXCEPTION: (PhutilJSONParserException) Parse error on line 0 at column 0: 'null' is not a valid JSON object. at [<arcanist>/src/parser/PhutilJSONParser.php:43]PHP message: arcanist(head=stable, ref.stable=5dd6ed0da533), moz-extensions(), phabricator()PHP message:   #0 <#2> PhutilJSONParser::parse(string) called at [<arcanist>/src/utils/utils.php:1314]PHP message:   #1 <#2> phutil_json_decode(string) called at [<moz-extensions>/differential/customfield/DifferentialUpliftRequestCustomField.php:409]PHP message:   #2 <#2> DifferentialUpliftRequestCustomField::setValue(string) called at [<moz-extensions>/differential/customfield/DifferentialUpliftRequestCustomField.php:403]PHP message:   #3 <#2> DifferentialUpliftRequestCustomField::setValueFromApplicationTransactions(string) called at [<phabricator>/src/infrastructure/customfield/editor/PhabricatorCustomFieldEditField.php:70]PHP message:   #4 <#2> PhabricatorCustomFieldEditField::buildControl() called at [<phabricator>/src/applications/transactions/editfield/PhabricatorEditField.php:376]PHP message:   #5 <#2> PhabricatorEditField::renderControl() called at [<phabricator>/src/applications/transactions/editfield/PhabricatorEditField.php:406]PHP message:   #6 <#2> PhabricatorEditField::appendToForm(AphrontFormView) called at [<phabricator>/src/applications/transactions/editengine/PhabricatorEditEngine.php:1384]PHP message:   #7 <#2> PhabricatorEditEngine::buildEditForm(DifferentialRevision, array) called at [<phabricator>/src/applications/transactions/editengine/PhabricatorEditEngine.php:1240]PHP message:   #8 <#2> PhabricatorEditEngine::buildEditResponse(DifferentialRevision) called at [<phabricator>/src/applications/transactions/editengine/PhabricatorEditEngine.php:998]PHP message:   #9 <#2> PhabricatorEditEngine::buildResponse() called at [<phabricator>/src/applications/differential/controller/DifferentialRevisionEditController.php:53

Any thoughts?

2022-03-02 17:00 UTC, dklawren commented on moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
> +        $body = phutil_json_decode($body);
nit-pick: spacing

2022-03-02 17:00 UTC, dklawren commented on moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
> +        }
More spacing fixes needed.

2022-03-02 17:00 UTC, dklawren commented on moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php
>      }
Spacing

2022-03-04 18:37 UTC, dklawren approved these changes
Works as expected now. r=dkl

2022-03-04 18:38 UTC, merged