Bug 1764136: improve styling of uplift request form
mozilla-conduit/phabricator pull request #21
Opened 2022-04-11 17:41 UTC by cgsheeh

Make the uplift request form use the `display: table` CSS
style to improve the appearance of the form. Change yes/no
answers in the form from a checkbox to a dropdown selection.
Add better validation of the form submission to server-side
processing.

2022-04-18 19:27 UTC, dklawren requested changes
Should we instead force them to make the Yes/No selection by having a default '--Select One--' option with value='' and then do not allow submit if they do not select Yes or No? Or are you fine with the defaults all set to 'Yes'?

Also I noticed the uplift action option is still available for revisions that do not have a bug ID assigned to it. If you try to create an uplift request, the fails on the backend with: 
"FastCGI sent in stderr: "PHP message: [2022-04-18 19:10:12] EXCEPTION: (TypeError) Argument 1 passed to DifferentialUpliftRequestCustomField::commentUpliftOnBugzilla() must be of the type int, string given, called in /app/moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php on line 392"

This is due to $bug = $bugzillaField->getValue(); being empty. We could fix this in a different bug/merge.

2022-04-18 19:31 UTC, cgsheeh commented
> Should we instead force them to make the Yes/No selection by having a default '--Select One--' option with value='' and then do not allow submit if they do not select Yes or No? Or are you fine with the defaults all set to 'Yes'?

That sounds like a good idea, I'll switch the form to do this instead.

> 
> Also I noticed the uplift action option is still available for revisions that do not have a bug ID assigned to it. If you try to create an uplift request, the fails on the backend with: "FastCGI sent in stderr: "PHP message: [2022-04-18 19:10:12] EXCEPTION: (TypeError) Argument 1 passed to DifferentialUpliftRequestCustomField::commentUpliftOnBugzilla() must be of the type int, string given, called in /app/moz-extensions/src/differential/customfield/DifferentialUpliftRequestCustomField.php on line 392"
> 
> This is due to $bug = $bugzillaField->getValue(); being empty. We could fix this in a different bug/merge.

Thanks for pointing that out - I'll fix it on the next iteration.

2022-04-19 17:34 UTC, dklawren requested changes
When editing an existing uplift form, the yes/no questions are not prefilled with the current values like the other fields. We should prefill the yes/no values as well. Otherwise working fine.

2022-04-21 20:34 UTC, merged

2022-04-21 20:36 UTC, dklawren commented
I will push this commit to phabricator-dev as well now so I can QA it along with other upstream changes I am working on.